export const plotOptions = [
	{ name: "CVD Barplot", route: "cvd-barplot" },
	{ name: "CVD Histogram", route: "cvd-histogram" },
	{ name: "Age Distribution", route: "age-distribution" },
	{ name: "Gender Analysis", route: "gender-analysis" },
	{ name: "Risk Factor Correlation", route: "risk-correlation" },
	{ name: "Treatment Outcomes", route: "treatment-outcomes" },
];

export const numericalFields: string[] = [
	"Sex",
	"PhysicalHealthDays",
	"MentalHealthDays",
	"HadAsthma",
	"LastCheckupTime",
	"HadDiabetes",
	"SmokerStatus",
	"AgeCategory",
	"AlcoholDrinkers",
	"Mobility",
	"PhysicalActivities",
	"HadCOPD",
	"HadKidneyDisease",
	"HadArthritis",
	"HaveHighCholesterol",
	"Sensory Impairments",
	"Vaccinated",
];

export const orderedKeys: string[] = [
	"Sex",
	"GeneralHealth",
	"PhysicalActivities",
	"HadAsthma",
	"HadCOPD",
	"HadKidneyDisease",
	"HadArthritis",
	"HadDiabetes",
	"SmokerStatus",
	"AgeCategory",
	"HeightInMeters",
	"WeightInKilograms",
	"BMI",
	"AlcoholDrinkers",
	"HaveHighCholesterol",
	"Sensory Impairments",
	"Vaccinated",
	"Mobility",
];
