export const numericalFields: string[] = [
	"Sex",
	"PhysicalHealthDays",
	"MentalHealthDays",
	"HadAsthma",
	"LastCheckupTime",
	"HadDiabetes",
	"SmokerStatus",
	"AgeCategory",
	"AlcoholDrinkers",
	"Mobility",
	"PhysicalActivities",
	"HadCOPD",
	"HadKidneyDisease",
	"HadArthritis",
	"HaveHighCholesterol",
	"Sensory Impairments",
	"Vaccinated",
];

export const orderedKeys: string[] = [
	"Sex",
	"GeneralHealth",
	"PhysicalActivities",
	"HadAsthma",
	"HadCOPD",
	"HadKidneyDisease",
	"HadArthritis",
	"HadDiabetes",
	"SmokerStatus",
	"AgeCategory",
	"HeightInMeters",
	"WeightInKilograms",
	"BMI",
	"AlcoholDrinkers",
	"HaveHighCholesterol",
	"Sensory Impairments",
	"Vaccinated",
	"Mobility",
];
