export const plotOptions = [
	{ name: "BMI Density Curve", route: "cvd-app/bmi_density" },
	{ name: "Body Mass Index", route: "cvd-app/bmi_distribution" },
	{ name: "Correlation Matrix", route: "cvd-app/corr_matrix" },
	{ name: "Chronic Conditions", route: "cvd-app/chronic_condition" },
	{ name: "Mobility Comparison", route: "cvd-app/mobility_issues" },
	{ name: "Risk Factor Prevalence", route: "cvd-app/risk_prevalence" },
];

export const numericalFields: string[] = [
	"Sex",
	"PhysicalHealthDays",
	"MentalHealthDays",
	"HadAsthma",
	"LastCheckupTime",
	"HadDiabetes",
	"SmokerStatus",
	"AgeCategory",
	"AlcoholDrinkers",
	"Mobility",
	"PhysicalActivities",
	"HadCOPD",
	"HadKidneyDisease",
	"HadArthritis",
	"HaveHighCholesterol",
	"Sensory Impairments",
	"Vaccinated",
];

export const orderedKeys: string[] = [
	"Sex",
	"GeneralHealth",
	"PhysicalActivities",
	"HadAsthma",
	"HadCOPD",
	"HadKidneyDisease",
	"HadArthritis",
	"HadDiabetes",
	"SmokerStatus",
	"AgeCategory",
	"HeightInMeters",
	"WeightInKilograms",
	"BMI",
	"AlcoholDrinkers",
	"HaveHighCholesterol",
	"Sensory Impairments",
	"Vaccinated",
	"Mobility",
];
